# SITE CONFIGURATION
title: Personal Page # your site title
author: Jordan Jasuta Fischer # You :P
description: > # Meta description of Homepage
  A collection of recent professional achievements and quick references for more info on the work I've done
# baseurl: toolbox # the subpath of your site, e.g. /blog
# url: "https://jordanjasuta.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://github.com/jordanjasuta

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  artificial intelligence platforms &middot; cognitive analytics &middot; open code &middot; 
  <br>
  civic technology &middot; geospatial analysis projects &middot; full stack development

hero_img: posts/suriname.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jordan.j.fischer@gmail.com # email for form submission

twitter_username:  jordanjasuta # replace with your_twitter_username or comment to remove link from footer
github_username:  jordanjasuta # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer

 disqus:
  shortname:  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
